# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/kedro-viz-lite',
                'doc_host': 'https://noklam.github.io',
                'git_url': 'https://github.com/noklam/kedro-viz-lite',
                'lib_path': 'kedro_viz_lite'},
  'syms': { 'kedro_viz_lite.core': {'kedro_viz_lite.core.foo': ('core.html#foo', 'kedro_viz_lite/core.py')},
            'kedro_viz_lite.hook': {'kedro_viz_lite.hook.foo': ('hook.html#foo', 'kedro_viz_lite/hook.py')}}}
